name: Release

on:
  workflow_dispatch: # Позволяет запускать вручную
  push:
    branches:
      - voice-over-patch

jobs:
  release:
    name: Create GitHub Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Release Body
        id: generate_body
        run: |
          echo "body=This release contains the custom Voice-Over Translation patch." >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.1-custom
          name: Custom Build with Voice-Over (v2)
          body: ${{ steps.generate_body.outputs.body }}
          files: |
            patches.json
          draft: false
          prerelease: false
