name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - voice-over-patch # Добавляем нашу ветку

jobs:
  release:
    name: Build and Release Artifacts
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build Jar
        run: ./gradlew clean jar --no-daemon

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: revanced-patches-jar
          path: build/libs/*.jar
